Flask_Blog/flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileRequired
from wtforms import FileField, StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    image = FileField('Image', validators=[FileRequired(), FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Post')


Flask_Blog/flaskblog/main/routes.py
from datetime import datetime

from flask import Blueprint, render_template, request
from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=9)
    return render_template('home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('about.html', title='About')


# payment_information() fonksiyonu
@main.route('/payment_information')
def payment_information():
    post_id = request.args.get('post_id', type=int)
    post = Post.query.get_or_404(post_id)
    # Fiyatı hesaplamak için, post id'sini 10 ile çarpın ve tarihin rakamlarının toplamını ekleyin
    date_digits = [int(d) for d in datetime.strftime(post.date_posted, '%Y%m%d%H%M%S')]
    price = post.id * 10 + sum(date_digits)

    # payment_information.html dosyasını render_template() fonksiyonuyla geri döndürün
    return render_template('payment_information.html', post=post, price=price)


@main.route('/process_payment', methods=['POST'])
def process_payment():
    # Ödeme işlemleri burada gerçekleştirilecek
    # ...
    return "Payment processed successfully!"

Flask_Blog/flaskblog/posts/routes.py
import os

from flask import (Blueprint, abort, current_app, flash, redirect,
                   render_template, request, url_for)
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm
from werkzeug.utils import secure_filename

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        image_file = None
        if form.image.data:
            image = form.image.data
            image_file = secure_filename(image.filename)
            image.save(os.path.join(current_app.root_path, 'static', 'post_images', image_file))
        post = Post(title=form.title.data, content=form.content.data, image_file=image_file, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        if form.image.data:
            image = form.image.data
            image_file = secure_filename(image.filename)
            image.save(os.path.join(current_app.root_path, 'static/post_images', image_file))
            post.image_file = image_file
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Yor post has been update!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
    form.title.data = post.title
    form.content.data = post.content
    return render_template('create_post.html', title='Update Post', 
                           form=form, legend='Update Post')
    
    
@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Yor post has been deleted!', 'success')
    return redirect(url_for('main.home'))


@posts.route("/post/<int:post_id>/purchase", methods=['PUT'])
@login_required
def purchase_post(post_id):
    post = Post.query.get_or_404(post_id)
    return redirect(url_for('main.payment_information'))

Flask_Blog/flaskblog/users/routes.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_dance.contrib.google import google, make_google_blueprint
from flask_login import current_user, login_required, login_user, logout_user
from flaskblog import bcrypt, db
from flaskblog.models import Post, User
from flaskblog.users.forms import (Loginform, RegistrationForm,
                                   RequestResetForm, ResetPasswordForm,
                                   UpdateAccountform)
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = Loginform()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check your email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountform()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)


@users.route("/google-login")
def google_login():
    if not google.authorized:
        return redirect(url_for('google.login'))
    resp = google.get("/oauth2/v2/userinfo")
    assert resp.ok, resp.text
    email = resp.json()["email"]
    user = User.query.filter_by(email=email).first()
    if user:
        login_user(user)
        return redirect(url_for('main.home'))
    else:
        flash('Login Unsuccessful. Please check your email and password', 'danger')
        return redirect(url_for('users.login'))


@users.route("/auth/google/callback")
def google_login_callback():
    if not google.authorized:
        return redirect(url_for('google.login'))
    resp = google.get("/oauth2/v2/userinfo")
    assert resp.ok, resp.text
    email = resp.json()["email"]
    user = User.query.filter_by(email=email).first()
    if user:
        login_user(user)
        return redirect(url_for('main.home'))
    else:
        flash('Login Unsuccessful. Please check your email and password', 'danger')
        return redirect(url_for('users.login'))

Flask_Blog/flaskblog/templates/about.html
{% extends "layout.html" %} {% block content %}


<section id="about">
        <div class="container mt-4 pt-4">
            <h1 class="text-center">Welcome to Our Food Blog!</h1>
            <div class="row mt-4">
                <div class="col-lg-4">
                    <img src="https://avatars.githubusercontent.com/u/58993751?s=400&u=884b46bda05402ebc8ba56a5693fae6102cc4137&v=4" class= "imageAboutPage" alt="">
                </div>

                <div class="col-lg-8">
                    <p> 
                     Our food blog is a place where food enthusiasts, home cooks, and professional
  chefs can come together to share their passion for creating delicious dishes.
  Here, you will find a variety of recipes, cooking tips, and culinary stories
  that will inspire you to explore new flavors and techniques in the kitchen.
                        
                    </p>
                    <p> 
                     Each of our contributors brings their unique perspective and expertise to the
  table, ensuring that there is always something new and exciting to discover.
  From traditional dishes to modern twists on classic favorites, our blog offers
  a diverse range of content to suit every palate and skill level.
                        
                    </p>
                    <p> 
                     Not only do we share mouthwatering recipes, but we also encourage our readers
  to share their own culinary creations and experiences. Whether you are a
  seasoned cook or just starting your culinary journey, we welcome you to join
  our community of like-minded individuals who share a love for all things food.
                        
                    </p>
                    <p> 
                    We hope you enjoy browsing our blog and trying out some of the delicious
  recipes and ideas we have to offer. Don't forget to share your creations with
  us – we love seeing what our readers have been cooking up!
                        
                    </p>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <ul>
                                <li>Name: Tuba Tosunoglu</li>
                                <li>Age: 28</li>
                                <li>Occupation: Web Developer</li>

                            </ul>
                        </div>
                        
                    </div>
                    <div class="row mt-3">
                    </div>
                </div>
            </div>
    </section>



{% endblock content %}


Flask_Blog/flaskblog/templates/create_post.html
{% extends "layout.html" %} {% block content %}
<div class="container">
  <h1 class="mt-4 mb-4 text-center">New Post</h1>
  <form method="POST" , enctype="multipart/form-data" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group mt-2">
      <legend class="border-bottom mb-4">Create a Post</legend>
      <div class="form-group mt-2">
        {{ form.title.label(class="form-control-label") }} {% if
        form.title.errors %} {{ form.title(class="form-control form-control-lg
        is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.title.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.title(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group mt-2">
        {{ form.content.label(class="form-control-label") }} {% if
        form.content.errors %} {{ form.content(class="form-control
        form-control-lg is-invalid") }}
        <div class="invalid-feedback">
          {% for error in form.content.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% else %} {{ form.content(class="form-control form-control-lg") }} {%
        endif %}
      </div>
      <div class="form-group mt-3">
        {{ form.image.label(class="form-control-label") }} {% if
        form.image.errors %}
        <div class="alert alert-danger" role="alert">
          {% for error in form.image.errors %}
          <p>{{ error }}</p>
          {% endfor %}
        </div>
        {% endif %} {{ form.image(class="form-control-file") }}
      </div>
     <!--  <form method="POST" enctype="multipart/form-data">
        <div class="form-group mt-3">
          <label for="file-input"></label>
          <input
            type="file"
            class="form-control-file"
            id="file-input"
            name="image"
            accept="image/*"
          />
        </div> 
      </form> -->
    </fieldset>
    <div class="form-group d-flex justify-content-center">
      <button class="btn btn-primary mt-2" type="submit">Post</button>
    </div>
  </form>
</div>
{% endblock content %}

Flask_Blog/flaskblog/templates/home.html
{% extends "layout.html" %} {% block content %}
<div class="container mt-1">
  <!-- <div
    id="carouselExampleIndicators"
    class="carousel slide mb-3"
    data-ride="carousel"
  >
    <ol class="carousel-indicators">
      <li
        data-target="#carouselExampleIndicators"
        data-slide-to="0"
        class="active"
      ></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img
          class="d-block w-100"
          src="static/carousel/1.jpeg"
          alt="First slide"
        />
      </div>
      <div class="carousel-item">
        <img
          class="d-block w-100"
          src="static/carousel/2.jpeg"
          alt="Second slide"
        />
      </div>
      <div class="carousel-item">
        <img
          class="d-block w-100"
          src="static/carousel/3.jpeg"
          alt="Third slide"
        />
      </div>
    </div>
    <a
      class="carousel-control-prev"
      href="#carouselExampleIndicators"
      role="button"
      data-slide="prev"
    >
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a
      class="carousel-control-next"
      href="#carouselExampleIndicators"
      role="button"
      data-slide="next"
    >
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div> -->
  <base />
  <div id="carousel">
    <figure id="spinner">
      <img src="https://avatars.mds.yandex.net/i?id=d14d7aee6901509e2b5df0f91149c424fed2e234-8249078-images-thumbs&n=13"
        alt />
      <img src="https://avatars.mds.yandex.net/i?id=d14d7aee6901509e2b5df0f91149c424fed2e234-8249078-images-thumbs&n=13"
        alt />
      <img src="https://avatars.mds.yandex.net/i?id=d14d7aee6901509e2b5df0f91149c424fed2e234-8249078-images-thumbs&n=13"
        alt />
      <img src="https://avatars.mds.yandex.net/i?id=d14d7aee6901509e2b5df0f91149c424fed2e234-8249078-images-thumbs&n=13"
        alt />
      <img src="https://avatars.mds.yandex.net/i?id=d14d7aee6901509e2b5df0f91149c424fed2e234-8249078-images-thumbs&n=13"
        alt />
      <img src="https://avatars.mds.yandex.net/i?id=d14d7aee6901509e2b5df0f91149c424fed2e234-8249078-images-thumbs&n=13"
        alt />
      <img src="https://avatars.mds.yandex.net/i?id=d14d7aee6901509e2b5df0f91149c424fed2e234-8249078-images-thumbs&n=13"
        alt />
      <img src="https://avatars.mds.yandex.net/i?id=d14d7aee6901509e2b5df0f91149c424fed2e234-8249078-images-thumbs&n=13"
        alt />
    </figure>
  </div>
  <span style="float: left" class="ss-icon" onclick="galleryspin('-')">&lt;</span>
  <span style="float: right" class="ss-icon" onclick="galleryspin('')">&gt;</span>
  <form class="form-inline my-2 my-lg-0 ">
    <div class="input-group mt-2">
      <input class="form-control mr-2" type="search" placeholder="Search for post" aria-label="Search">
      <div class="input-group-append mr-2">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </div>
    </div>
  </form>
 <div class="row mt-4">
  {% if posts %}
  {% set post_count = 0 %}
  {% for post in posts.items %}
    {% if post_count < 9 %}
      <div class="col-md-4 mb-4">
        <div class="card box-shadow h-100">
          {% if post.image_file %}
          <img class="card-img-top" src="{{ url_for('static', filename='post_images/' + post.image_file) }}"
            alt="post image">
          {% endif %}
          <div class="card-body d-flex flex-column">
            <h5 class="card-title text-center"><a href="{{ url_for('posts.post', post_id=post.id) }}" class="post-title">{{ post.title }}</a></h5>

            <div class="card-text" style="height: 100px; overflow: auto;">
              {{ post.content }}
            </div>
            <div class="d-flex justify-content-between align-items-center mt-3 mt-auto">
              <div class="btn-group d-flex align-items-center">
                {% if post.author != current_user %}
                <form action="{{ url_for('main.payment_information') }}" method="GET">
                  <input type="hidden" name="post_id" value="{{ post.id }}">
                  <button type="submit" class="btn btn-sm btn-outline-primary m-1">Buy</button>
                  <a href="{{ url_for('posts.post', post_id=post.id) }}" class="btn btn-sm btn-outline-info">Show More</a>
                </form>
                {% else %}
                <a href="{{ url_for('posts.update_post', post_id=post.id) }}"
                  class="btn btn-sm btn-outline-secondary">Update</a>
                <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal"
                  data-target="#deleteModal">Delete</button>
                  <div
                  class="modal fade"
                  id="deleteModal"
                  tabindex="-1"
                  role="dialog"
                  aria-labelledby="deleteModalLabel"
                  aria-hidden="true"
                >
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
                        <button
                          type="button"
                          class="close"
                          data-dismiss="modal"
                          aria-label="Close"
                        >
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                          Close
                        </button>
                        <form
                          action="{{ url_for('posts.delete_post', post_id=post.id) }}"
                          method="POST">
                          <input class="btn btn-danger" type="submit" value="Delete" />
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
                <a href="{{ url_for('posts.post', post_id=post.id) }}" class="btn btn-sm btn-outline-info">Show More</a>
                {% endif %}
              </div>
              <small class="text-muted">${{ post.price }}</small>
            </div>
          </div>
        </div>
      </div>
      {% set post_count = post_count + 1 %}
    {% endif %}
  {% endfor %}
  {% endif %}
</div>


<nav aria-label="Page navigation">
  <ul class="pagination">
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=2, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <li class="page-item active"><a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num
              }}</a></li>
        {% else %}
    <li class="page-item"><a class="page-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></li>
    {% endif %}
    {% else %}
    <li class="page-item disabled"><span class="page-link">...</span></li>
    {% endif %}
    {% endfor %}
  </ul>
</nav>


</div>

{% endblock content %}
</div>

</div>

Flask_Blog/flaskblog/templates/login.html
{% extends "layout.html" %} {% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="content-section mt-5">
        <h2 class="text-center mt-2">Log In</h2>
        <form method="POST" , action="">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <div class="form-group">
              {{ form.email.label(class="form-control-label") }} {% if
              form.email.errors %} {{ form.email(class="form-control
              form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.email(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group mt-1">
              {{ form.password.label(class="form-control-label") }} {% if
              form.password.errors %} {{ form.password(class="form-control
              form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.password.errors %}
                <span>{{ error }}</span>
                {% endfor %}
              </div>
              {% else %} {{ form.password(class="form-control form-control-lg")
              }} {% endif %}
            </div>
            <div class="form-group mt-1">
              <a
                href="{{ url_for('users.google_login') }}"
                class="btn btn-outline-danger mt-2"
                >Sign in with Google</a
              >
            </div>
            <div class="form-check mt-2">
              {{ form.remember(class="form-check-input") }} {{
              form.remember.label(class="form-check-label") }}
            </div>
          </fieldset>
<div class="form-group mt-2 d-flex justify-content-center">
            {{ form.submit(class="btn btn-primary btn-block") }}
            </div>

            <small class="text-muted d-block text-center mt-3">
              <a href="{{ url_for('users.reset_request') }}"
                >Forgot Password?</a
              >
            </small>
          </div>
        </form>
      </div>
      <div class="border-top pt-3 mt-4">
        <small class="text-muted d-block text-center">
          Need An Account?
          <a href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

Flask_Blog/flaskblog/templates/payment_information.html
{% extends "layout.html" %} {% block content %}
<div class="container mt-5 d-flex flex-column align-items-center">
  <h1 class="mb-4">Payment Information</h1>
  <p class="mb-4">The price of the post is ${{ price }}.</p>
  <form
    action="{{ url_for('main.process_payment', post_id=post.id) }}"
    method="POST"
    class="w-50"
  >
    <div class="form-group mb-3">
      <label for="payment_method" class="form-label"
        >Select Payment Method:</label
      >
      <select class="form-select" id="payment_method">
        <option>Credit Card</option>
        <option>PayPal</option>
        <option>Bank Transfer</option>
      </select>
    </div>
    <button type="submit" class="btn btn-primary mx-auto d-block">
      Submit Payment
    </button>
  </form>
</div>
{% endblock content %}

Flask_Blog/flaskblog/templates/post.html
{% extends "layout.html" %} {% block content %}
<article class="media contenrt-section mt-3">
  <div style="text-align: center">
    <img
      class="rounded-circle article-img"
      src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
      style="width: 100px; height: 100px"
    />
  </div>
  <div class="media-body mt-2" style="text-align: center">
    <div class="article-metadata">
      <div>
        <a
          class="mr-2"
          href="{{ url_for('users.user_posts', username=post.author.username) }}"
          >{{ post.author.username }}</a
        >
      </div>
      <div class="text-muted mt-2">
        {{ post.date_posted.strftime('%Y-%m-%d') }}
      </div>
      {% if post.image_file %}
              <img class="card-img-top" src="{{ url_for('static', filename='post_images/' + post.image_file) }}" alt="post image">
      {% endif %}
    </div>
    <h2 class="article-title">{{ post.title }}</h2>
    <textarea
      class="form-control"
      rows="5"
      style="resize: none; overflow: auto"
    >
{{ post.content }}</textarea
    >
  </div>
  <div class="btn-group">
    {% if post.author == current_user %}
    <div>
      <a
        class="btn btn-secondary btn-sm mb-1"
        href="{{ url_for('posts.update_post', post_id=post.id) }}"
        >Update</a
      >
      <button
        type="button"
        ,
        class="btn btn-danger btn-sm m-1"
        data-toggle="modal"
        data-target="#deleteModal"
      >
        Delete
      </button>
    </div>
    {% else %}
      <button type="submit" class="btn btn-sm btn-outline-primary m-1">Buy</button>
    {% endif %}
  </div>
</article>
<!-- Modal -->
<div
  class="modal fade"
  id="deleteModal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="deleteModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
        <button
          type="button"
          class="close"
          data-dismiss="modal"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <form
          action="{{ url_for('posts.delete_post', post_id=post.id) }}"
          method="POST"
        >
          <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

Flask_Blog/flaskblog/templates/user_posts.html
{% extends "layout.html" %} {% block content %}
<h1 class="mb-3 mt-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
{% for post in posts.items %}
<article class="media content-section">
  <div style="text-align: center">
    <img
      class="rounded-circle article-img"
      src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}"
      style="width: 100px; height: 100px"
    />
  </div>
  <div class="media-body mt-2" style="text-align: center">
    <div class="article-metadata">
      <a
        class="mr-2"
        href="{{ url_for('users.user_posts', username=post.author.username) }}"
        >{{ post.author.username }}</a
      >
    </div>
    <div class="text-muted mt-2">
      {{ post.date_posted.strftime('%Y-%m-%d') }}
    </div>
    <h2>
      {% if post.image_file %}
      <img class="card-img-top" src="{{ url_for('static', filename='post_images/' + post.image_file) }}" alt="post image">
      {% endif %}
      <a
        class="article-title"
        href="{{ url_for('posts.post', post_id=post.id) }}"
        >{{ post.title }}</a
      >
    </h2>
    <p class="article-content">{{ post.content }}</p>
  </div>
</article>
{% endfor %} {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,
left_current=1, right_current=2) %} {% if page_num %} {% if posts.page ==
page_num %}
<a
  class="btn btn-info mb-4"
  href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"
  >{{ page_num }}</a
>
{% else %}
<a
  class="btn btn-outline-info mb-4"
  href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}"
  >{{ page_num }}</a
>
{% endif %} {% else %} ... {% endif %} {% endfor %} {% endblock content %}